/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jagex_framework_net_socket_jagsock */

#ifndef _Included_com_jagex_framework_net_socket_jagsock
#define _Included_com_jagex_framework_net_socket_jagsock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_listen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1listen__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_listen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1listen__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_connect
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1connect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_isconnected
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1isconnected
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_accept
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1accept
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1read
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_jagex_framework_net_socket_jagsock
 * Method:    imp_bufsize
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_jagex_framework_net_socket_jagsock_imp_1bufsize
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
